// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonConst.proto

package com.wmj.game.common.message.core;

/**
 * Protobuf enum {@code Cmd}
 */
public enum Cmd
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UnKnow = 0;</code>
   */
  UnKnow(0),
  /**
   * <pre>
   *内部
   * </pre>
   *
   * <code>ChangeRoleServerReq = 1005;</code>
   */
  ChangeRoleServerReq(1005),
  /**
   * <pre>
   *改变角色服务器
   * </pre>
   *
   * <code>ChangeRoleServerRes = 1006;</code>
   */
  ChangeRoleServerRes(1006),
  /**
   * <pre>
   *网关
   * </pre>
   *
   * <code>Ping = 5001;</code>
   */
  Ping(5001),
  /**
   * <pre>
   *ping返回
   * </pre>
   *
   * <code>Pong = 5002;</code>
   */
  Pong(5002),
  /**
   * <pre>
   *大厅
   * </pre>
   *
   * <code>LoginReq = 10001;</code>
   */
  LoginReq(10001),
  /**
   * <pre>
   *登录
   * </pre>
   *
   * <code>LoginRes = 10002;</code>
   */
  LoginRes(10002),
  /**
   * <pre>
   *退出游戏
   * </pre>
   *
   * <code>QuitReq = 10007;</code>
   */
  QuitReq(10007),
  /**
   * <pre>
   *退出游戏
   * </pre>
   *
   * <code>QuitRes = 10008;</code>
   */
  QuitRes(10008),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UnKnow = 0;</code>
   */
  public static final int UnKnow_VALUE = 0;
  /**
   * <pre>
   *内部
   * </pre>
   *
   * <code>ChangeRoleServerReq = 1005;</code>
   */
  public static final int ChangeRoleServerReq_VALUE = 1005;
  /**
   * <pre>
   *改变角色服务器
   * </pre>
   *
   * <code>ChangeRoleServerRes = 1006;</code>
   */
  public static final int ChangeRoleServerRes_VALUE = 1006;
  /**
   * <pre>
   *网关
   * </pre>
   *
   * <code>Ping = 5001;</code>
   */
  public static final int Ping_VALUE = 5001;
  /**
   * <pre>
   *ping返回
   * </pre>
   *
   * <code>Pong = 5002;</code>
   */
  public static final int Pong_VALUE = 5002;
  /**
   * <pre>
   *大厅
   * </pre>
   *
   * <code>LoginReq = 10001;</code>
   */
  public static final int LoginReq_VALUE = 10001;
  /**
   * <pre>
   *登录
   * </pre>
   *
   * <code>LoginRes = 10002;</code>
   */
  public static final int LoginRes_VALUE = 10002;
  /**
   * <pre>
   *退出游戏
   * </pre>
   *
   * <code>QuitReq = 10007;</code>
   */
  public static final int QuitReq_VALUE = 10007;
  /**
   * <pre>
   *退出游戏
   * </pre>
   *
   * <code>QuitRes = 10008;</code>
   */
  public static final int QuitRes_VALUE = 10008;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Cmd valueOf(int value) {
    return forNumber(value);
  }

  public static Cmd forNumber(int value) {
    switch (value) {
      case 0: return UnKnow;
      case 1005: return ChangeRoleServerReq;
      case 1006: return ChangeRoleServerRes;
      case 5001: return Ping;
      case 5002: return Pong;
      case 10001: return LoginReq;
      case 10002: return LoginRes;
      case 10007: return QuitReq;
      case 10008: return QuitRes;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Cmd> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
          public Cmd findValueByNumber(int number) {
            return Cmd.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.wmj.game.common.message.core.CommonConst.getDescriptor().getEnumTypes().get(1);
  }

  private static final Cmd[] VALUES = values();

  public static Cmd valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Cmd(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Cmd)
}

