// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GatewayMessage.proto

package com.wmj.game.common.message.core;

public final class GatewayMessage {
  private GatewayMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Cmd cmd = 1;</code>
     */
    int getCmdValue();
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    com.wmj.game.common.message.core.Cmd getCmd();
  }
  /**
   * Protobuf type {@code PingReq}
   */
  public  static final class PingReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingReq)
      PingReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingReq.newBuilder() to construct.
    private PingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingReq() {
      cmd_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_PingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_PingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.common.message.core.GatewayMessage.PingReq.class, com.wmj.game.common.message.core.GatewayMessage.PingReq.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public com.wmj.game.common.message.core.Cmd getCmd() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
      return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.common.message.core.GatewayMessage.PingReq)) {
        return super.equals(obj);
      }
      com.wmj.game.common.message.core.GatewayMessage.PingReq other = (com.wmj.game.common.message.core.GatewayMessage.PingReq) obj;

      boolean result = true;
      result = result && cmd_ == other.cmd_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PingReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.common.message.core.GatewayMessage.PingReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PingReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingReq)
        com.wmj.game.common.message.core.GatewayMessage.PingReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PingReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PingReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.common.message.core.GatewayMessage.PingReq.class, com.wmj.game.common.message.core.GatewayMessage.PingReq.Builder.class);
      }

      // Construct using com.wmj.game.common.message.core.GatewayMessage.PingReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PingReq_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PingReq getDefaultInstanceForType() {
        return com.wmj.game.common.message.core.GatewayMessage.PingReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PingReq build() {
        com.wmj.game.common.message.core.GatewayMessage.PingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PingReq buildPartial() {
        com.wmj.game.common.message.core.GatewayMessage.PingReq result = new com.wmj.game.common.message.core.GatewayMessage.PingReq(this);
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.common.message.core.GatewayMessage.PingReq) {
          return mergeFrom((com.wmj.game.common.message.core.GatewayMessage.PingReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.common.message.core.GatewayMessage.PingReq other) {
        if (other == com.wmj.game.common.message.core.GatewayMessage.PingReq.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.common.message.core.GatewayMessage.PingReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.common.message.core.GatewayMessage.PingReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public com.wmj.game.common.message.core.Cmd getCmd() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
        return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmd(com.wmj.game.common.message.core.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PingReq)
    }

    // @@protoc_insertion_point(class_scope:PingReq)
    private static final com.wmj.game.common.message.core.GatewayMessage.PingReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.common.message.core.GatewayMessage.PingReq();
    }

    public static com.wmj.game.common.message.core.GatewayMessage.PingReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingReq>
        PARSER = new com.google.protobuf.AbstractParser<PingReq>() {
      @java.lang.Override
      public PingReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.common.message.core.GatewayMessage.PingReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PongRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Cmd cmd = 1;</code>
     */
    int getCmdValue();
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    com.wmj.game.common.message.core.Cmd getCmd();

    /**
     * <code>int32 errorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>int64 systemTime = 3;</code>
     */
    long getSystemTime();
  }
  /**
   * Protobuf type {@code PongRes}
   */
  public  static final class PongRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PongRes)
      PongResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PongRes.newBuilder() to construct.
    private PongRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PongRes() {
      cmd_ = 0;
      errorCode_ = 0;
      systemTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PongRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 16: {

              errorCode_ = input.readInt32();
              break;
            }
            case 24: {

              systemTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_PongRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_PongRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.common.message.core.GatewayMessage.PongRes.class, com.wmj.game.common.message.core.GatewayMessage.PongRes.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public com.wmj.game.common.message.core.Cmd getCmd() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
      return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int SYSTEMTIME_FIELD_NUMBER = 3;
    private long systemTime_;
    /**
     * <code>int64 systemTime = 3;</code>
     */
    public long getSystemTime() {
      return systemTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(2, errorCode_);
      }
      if (systemTime_ != 0L) {
        output.writeInt64(3, systemTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (systemTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, systemTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.common.message.core.GatewayMessage.PongRes)) {
        return super.equals(obj);
      }
      com.wmj.game.common.message.core.GatewayMessage.PongRes other = (com.wmj.game.common.message.core.GatewayMessage.PongRes) obj;

      boolean result = true;
      result = result && cmd_ == other.cmd_;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && (getSystemTime()
          == other.getSystemTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + SYSTEMTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSystemTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.PongRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.common.message.core.GatewayMessage.PongRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PongRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PongRes)
        com.wmj.game.common.message.core.GatewayMessage.PongResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PongRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PongRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.common.message.core.GatewayMessage.PongRes.class, com.wmj.game.common.message.core.GatewayMessage.PongRes.Builder.class);
      }

      // Construct using com.wmj.game.common.message.core.GatewayMessage.PongRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        errorCode_ = 0;

        systemTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_PongRes_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PongRes getDefaultInstanceForType() {
        return com.wmj.game.common.message.core.GatewayMessage.PongRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PongRes build() {
        com.wmj.game.common.message.core.GatewayMessage.PongRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.PongRes buildPartial() {
        com.wmj.game.common.message.core.GatewayMessage.PongRes result = new com.wmj.game.common.message.core.GatewayMessage.PongRes(this);
        result.cmd_ = cmd_;
        result.errorCode_ = errorCode_;
        result.systemTime_ = systemTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.common.message.core.GatewayMessage.PongRes) {
          return mergeFrom((com.wmj.game.common.message.core.GatewayMessage.PongRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.common.message.core.GatewayMessage.PongRes other) {
        if (other == com.wmj.game.common.message.core.GatewayMessage.PongRes.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.getSystemTime() != 0L) {
          setSystemTime(other.getSystemTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.common.message.core.GatewayMessage.PongRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.common.message.core.GatewayMessage.PongRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public com.wmj.game.common.message.core.Cmd getCmd() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
        return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmd(com.wmj.game.common.message.core.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private long systemTime_ ;
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public long getSystemTime() {
        return systemTime_;
      }
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public Builder setSystemTime(long value) {
        
        systemTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public Builder clearSystemTime() {
        
        systemTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PongRes)
    }

    // @@protoc_insertion_point(class_scope:PongRes)
    private static final com.wmj.game.common.message.core.GatewayMessage.PongRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.common.message.core.GatewayMessage.PongRes();
    }

    public static com.wmj.game.common.message.core.GatewayMessage.PongRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PongRes>
        PARSER = new com.google.protobuf.AbstractParser<PongRes>() {
      @java.lang.Override
      public PongRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PongRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PongRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PongRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.common.message.core.GatewayMessage.PongRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReconnectResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReconnectRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Cmd cmd = 1;</code>
     */
    int getCmdValue();
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    com.wmj.game.common.message.core.Cmd getCmd();
  }
  /**
   * Protobuf type {@code ReconnectRes}
   */
  public  static final class ReconnectRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReconnectRes)
      ReconnectResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReconnectRes.newBuilder() to construct.
    private ReconnectRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReconnectRes() {
      cmd_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReconnectRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_ReconnectRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.common.message.core.GatewayMessage.internal_static_ReconnectRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.class, com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.Cmd cmd = 1;</code>
     */
    public com.wmj.game.common.message.core.Cmd getCmd() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
      return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.wmj.game.common.message.core.Cmd.UnKnow.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.common.message.core.GatewayMessage.ReconnectRes)) {
        return super.equals(obj);
      }
      com.wmj.game.common.message.core.GatewayMessage.ReconnectRes other = (com.wmj.game.common.message.core.GatewayMessage.ReconnectRes) obj;

      boolean result = true;
      result = result && cmd_ == other.cmd_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.common.message.core.GatewayMessage.ReconnectRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReconnectRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReconnectRes)
        com.wmj.game.common.message.core.GatewayMessage.ReconnectResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_ReconnectRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_ReconnectRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.class, com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.Builder.class);
      }

      // Construct using com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.common.message.core.GatewayMessage.internal_static_ReconnectRes_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.ReconnectRes getDefaultInstanceForType() {
        return com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.ReconnectRes build() {
        com.wmj.game.common.message.core.GatewayMessage.ReconnectRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.common.message.core.GatewayMessage.ReconnectRes buildPartial() {
        com.wmj.game.common.message.core.GatewayMessage.ReconnectRes result = new com.wmj.game.common.message.core.GatewayMessage.ReconnectRes(this);
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.common.message.core.GatewayMessage.ReconnectRes) {
          return mergeFrom((com.wmj.game.common.message.core.GatewayMessage.ReconnectRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.common.message.core.GatewayMessage.ReconnectRes other) {
        if (other == com.wmj.game.common.message.core.GatewayMessage.ReconnectRes.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.common.message.core.GatewayMessage.ReconnectRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.common.message.core.GatewayMessage.ReconnectRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public com.wmj.game.common.message.core.Cmd getCmd() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.core.Cmd result = com.wmj.game.common.message.core.Cmd.valueOf(cmd_);
        return result == null ? com.wmj.game.common.message.core.Cmd.UNRECOGNIZED : result;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder setCmd(com.wmj.game.common.message.core.Cmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Cmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReconnectRes)
    }

    // @@protoc_insertion_point(class_scope:ReconnectRes)
    private static final com.wmj.game.common.message.core.GatewayMessage.ReconnectRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.common.message.core.GatewayMessage.ReconnectRes();
    }

    public static com.wmj.game.common.message.core.GatewayMessage.ReconnectRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReconnectRes>
        PARSER = new com.google.protobuf.AbstractParser<ReconnectRes>() {
      @java.lang.Override
      public ReconnectRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReconnectRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReconnectRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReconnectRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.common.message.core.GatewayMessage.ReconnectRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReconnectRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReconnectRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GatewayMessage.proto\032\021CommonConst.prot" +
      "o\"\034\n\007PingReq\022\021\n\003cmd\030\001 \001(\0162\004.Cmd\"C\n\007PongR" +
      "es\022\021\n\003cmd\030\001 \001(\0162\004.Cmd\022\021\n\terrorCode\030\002 \001(\005" +
      "\022\022\n\nsystemTime\030\003 \001(\003\"!\n\014ReconnectRes\022\021\n\003" +
      "cmd\030\001 \001(\0162\004.CmdB\"\n com.wmj.game.common.m" +
      "essage.coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wmj.game.common.message.core.CommonConst.getDescriptor(),
        }, assigner);
    internal_static_PingReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingReq_descriptor,
        new java.lang.String[] { "Cmd", });
    internal_static_PongRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PongRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongRes_descriptor,
        new java.lang.String[] { "Cmd", "ErrorCode", "SystemTime", });
    internal_static_ReconnectRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReconnectRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReconnectRes_descriptor,
        new java.lang.String[] { "Cmd", });
    com.wmj.game.common.message.core.CommonConst.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
