// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GatewayMessage.proto

package com.wmj.game.common.message.code;

public final class GatewayMessage {
  private GatewayMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MID mid = 1;</code>
     */
    int getMidValue();
    /**
     * <code>.MID mid = 1;</code>
     */
    com.wmj.game.common.message.code.Mid.MID getMid();
  }
  /**
   * Protobuf type {@code ping}
   */
  public  static final class ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ping)
      pingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ping.newBuilder() to construct.
    private ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ping() {
      mid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              mid_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.common.message.code.GatewayMessage.internal_static_ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.common.message.code.GatewayMessage.internal_static_ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.common.message.code.GatewayMessage.ping.class, com.wmj.game.common.message.code.GatewayMessage.ping.Builder.class);
    }

    public static final int MID_FIELD_NUMBER = 1;
    private int mid_;
    /**
     * <code>.MID mid = 1;</code>
     */
    public int getMidValue() {
      return mid_;
    }
    /**
     * <code>.MID mid = 1;</code>
     */
    public com.wmj.game.common.message.code.Mid.MID getMid() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.code.Mid.MID result = com.wmj.game.common.message.code.Mid.MID.valueOf(mid_);
      return result == null ? com.wmj.game.common.message.code.Mid.MID.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mid_ != com.wmj.game.common.message.code.Mid.MID.Unknow.getNumber()) {
        output.writeEnum(1, mid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mid_ != com.wmj.game.common.message.code.Mid.MID.Unknow.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.common.message.code.GatewayMessage.ping)) {
        return super.equals(obj);
      }
      com.wmj.game.common.message.code.GatewayMessage.ping other = (com.wmj.game.common.message.code.GatewayMessage.ping) obj;

      boolean result = true;
      result = result && mid_ == other.mid_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + mid_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.common.message.code.GatewayMessage.ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ping)
        com.wmj.game.common.message.code.GatewayMessage.pingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_ping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.common.message.code.GatewayMessage.ping.class, com.wmj.game.common.message.code.GatewayMessage.ping.Builder.class);
      }

      // Construct using com.wmj.game.common.message.code.GatewayMessage.ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mid_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_ping_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.ping getDefaultInstanceForType() {
        return com.wmj.game.common.message.code.GatewayMessage.ping.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.ping build() {
        com.wmj.game.common.message.code.GatewayMessage.ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.ping buildPartial() {
        com.wmj.game.common.message.code.GatewayMessage.ping result = new com.wmj.game.common.message.code.GatewayMessage.ping(this);
        result.mid_ = mid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.common.message.code.GatewayMessage.ping) {
          return mergeFrom((com.wmj.game.common.message.code.GatewayMessage.ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.common.message.code.GatewayMessage.ping other) {
        if (other == com.wmj.game.common.message.code.GatewayMessage.ping.getDefaultInstance()) return this;
        if (other.mid_ != 0) {
          setMidValue(other.getMidValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.common.message.code.GatewayMessage.ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.common.message.code.GatewayMessage.ping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mid_ = 0;
      /**
       * <code>.MID mid = 1;</code>
       */
      public int getMidValue() {
        return mid_;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder setMidValue(int value) {
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public com.wmj.game.common.message.code.Mid.MID getMid() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.code.Mid.MID result = com.wmj.game.common.message.code.Mid.MID.valueOf(mid_);
        return result == null ? com.wmj.game.common.message.code.Mid.MID.UNRECOGNIZED : result;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder setMid(com.wmj.game.common.message.code.Mid.MID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mid_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder clearMid() {
        
        mid_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ping)
    }

    // @@protoc_insertion_point(class_scope:ping)
    private static final com.wmj.game.common.message.code.GatewayMessage.ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.common.message.code.GatewayMessage.ping();
    }

    public static com.wmj.game.common.message.code.GatewayMessage.ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ping>
        PARSER = new com.google.protobuf.AbstractParser<ping>() {
      @java.lang.Override
      public ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.common.message.code.GatewayMessage.ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface pongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MID mid = 1;</code>
     */
    int getMidValue();
    /**
     * <code>.MID mid = 1;</code>
     */
    com.wmj.game.common.message.code.Mid.MID getMid();

    /**
     * <code>.Code errorCode = 2;</code>
     */
    int getErrorCodeValue();
    /**
     * <code>.Code errorCode = 2;</code>
     */
    com.wmj.game.common.message.code.ErrorCode.Code getErrorCode();

    /**
     * <code>int64 systemTime = 3;</code>
     */
    long getSystemTime();
  }
  /**
   * Protobuf type {@code pong}
   */
  public  static final class pong extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pong)
      pongOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pong.newBuilder() to construct.
    private pong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pong() {
      mid_ = 0;
      errorCode_ = 0;
      systemTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pong(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              mid_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              errorCode_ = rawValue;
              break;
            }
            case 24: {

              systemTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.common.message.code.GatewayMessage.internal_static_pong_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.common.message.code.GatewayMessage.internal_static_pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.common.message.code.GatewayMessage.pong.class, com.wmj.game.common.message.code.GatewayMessage.pong.Builder.class);
    }

    public static final int MID_FIELD_NUMBER = 1;
    private int mid_;
    /**
     * <code>.MID mid = 1;</code>
     */
    public int getMidValue() {
      return mid_;
    }
    /**
     * <code>.MID mid = 1;</code>
     */
    public com.wmj.game.common.message.code.Mid.MID getMid() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.code.Mid.MID result = com.wmj.game.common.message.code.Mid.MID.valueOf(mid_);
      return result == null ? com.wmj.game.common.message.code.Mid.MID.UNRECOGNIZED : result;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>.Code errorCode = 2;</code>
     */
    public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <code>.Code errorCode = 2;</code>
     */
    public com.wmj.game.common.message.code.ErrorCode.Code getErrorCode() {
      @SuppressWarnings("deprecation")
      com.wmj.game.common.message.code.ErrorCode.Code result = com.wmj.game.common.message.code.ErrorCode.Code.valueOf(errorCode_);
      return result == null ? com.wmj.game.common.message.code.ErrorCode.Code.UNRECOGNIZED : result;
    }

    public static final int SYSTEMTIME_FIELD_NUMBER = 3;
    private long systemTime_;
    /**
     * <code>int64 systemTime = 3;</code>
     */
    public long getSystemTime() {
      return systemTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mid_ != com.wmj.game.common.message.code.Mid.MID.Unknow.getNumber()) {
        output.writeEnum(1, mid_);
      }
      if (errorCode_ != com.wmj.game.common.message.code.ErrorCode.Code.Success.getNumber()) {
        output.writeEnum(2, errorCode_);
      }
      if (systemTime_ != 0L) {
        output.writeInt64(3, systemTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mid_ != com.wmj.game.common.message.code.Mid.MID.Unknow.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mid_);
      }
      if (errorCode_ != com.wmj.game.common.message.code.ErrorCode.Code.Success.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errorCode_);
      }
      if (systemTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, systemTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.common.message.code.GatewayMessage.pong)) {
        return super.equals(obj);
      }
      com.wmj.game.common.message.code.GatewayMessage.pong other = (com.wmj.game.common.message.code.GatewayMessage.pong) obj;

      boolean result = true;
      result = result && mid_ == other.mid_;
      result = result && errorCode_ == other.errorCode_;
      result = result && (getSystemTime()
          == other.getSystemTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + mid_;
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + errorCode_;
      hash = (37 * hash) + SYSTEMTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSystemTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.common.message.code.GatewayMessage.pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.common.message.code.GatewayMessage.pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pong)
        com.wmj.game.common.message.code.GatewayMessage.pongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_pong_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.common.message.code.GatewayMessage.pong.class, com.wmj.game.common.message.code.GatewayMessage.pong.Builder.class);
      }

      // Construct using com.wmj.game.common.message.code.GatewayMessage.pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mid_ = 0;

        errorCode_ = 0;

        systemTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.common.message.code.GatewayMessage.internal_static_pong_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.pong getDefaultInstanceForType() {
        return com.wmj.game.common.message.code.GatewayMessage.pong.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.pong build() {
        com.wmj.game.common.message.code.GatewayMessage.pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.common.message.code.GatewayMessage.pong buildPartial() {
        com.wmj.game.common.message.code.GatewayMessage.pong result = new com.wmj.game.common.message.code.GatewayMessage.pong(this);
        result.mid_ = mid_;
        result.errorCode_ = errorCode_;
        result.systemTime_ = systemTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.common.message.code.GatewayMessage.pong) {
          return mergeFrom((com.wmj.game.common.message.code.GatewayMessage.pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.common.message.code.GatewayMessage.pong other) {
        if (other == com.wmj.game.common.message.code.GatewayMessage.pong.getDefaultInstance()) return this;
        if (other.mid_ != 0) {
          setMidValue(other.getMidValue());
        }
        if (other.errorCode_ != 0) {
          setErrorCodeValue(other.getErrorCodeValue());
        }
        if (other.getSystemTime() != 0L) {
          setSystemTime(other.getSystemTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.common.message.code.GatewayMessage.pong parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.common.message.code.GatewayMessage.pong) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mid_ = 0;
      /**
       * <code>.MID mid = 1;</code>
       */
      public int getMidValue() {
        return mid_;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder setMidValue(int value) {
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public com.wmj.game.common.message.code.Mid.MID getMid() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.code.Mid.MID result = com.wmj.game.common.message.code.Mid.MID.valueOf(mid_);
        return result == null ? com.wmj.game.common.message.code.Mid.MID.UNRECOGNIZED : result;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder setMid(com.wmj.game.common.message.code.Mid.MID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mid_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MID mid = 1;</code>
       */
      public Builder clearMid() {
        
        mid_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ = 0;
      /**
       * <code>.Code errorCode = 2;</code>
       */
      public int getErrorCodeValue() {
        return errorCode_;
      }
      /**
       * <code>.Code errorCode = 2;</code>
       */
      public Builder setErrorCodeValue(int value) {
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Code errorCode = 2;</code>
       */
      public com.wmj.game.common.message.code.ErrorCode.Code getErrorCode() {
        @SuppressWarnings("deprecation")
        com.wmj.game.common.message.code.ErrorCode.Code result = com.wmj.game.common.message.code.ErrorCode.Code.valueOf(errorCode_);
        return result == null ? com.wmj.game.common.message.code.ErrorCode.Code.UNRECOGNIZED : result;
      }
      /**
       * <code>.Code errorCode = 2;</code>
       */
      public Builder setErrorCode(com.wmj.game.common.message.code.ErrorCode.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Code errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private long systemTime_ ;
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public long getSystemTime() {
        return systemTime_;
      }
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public Builder setSystemTime(long value) {
        
        systemTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 systemTime = 3;</code>
       */
      public Builder clearSystemTime() {
        
        systemTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pong)
    }

    // @@protoc_insertion_point(class_scope:pong)
    private static final com.wmj.game.common.message.code.GatewayMessage.pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.common.message.code.GatewayMessage.pong();
    }

    public static com.wmj.game.common.message.code.GatewayMessage.pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pong>
        PARSER = new com.google.protobuf.AbstractParser<pong>() {
      @java.lang.Override
      public pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pong(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pong> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.common.message.code.GatewayMessage.pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GatewayMessage.proto\032\tMid.proto\032\017Error" +
      "Code.proto\"\031\n\004ping\022\021\n\003mid\030\001 \001(\0162\004.MID\"G\n" +
      "\004pong\022\021\n\003mid\030\001 \001(\0162\004.MID\022\030\n\terrorCode\030\002 " +
      "\001(\0162\005.Code\022\022\n\nsystemTime\030\003 \001(\003B\"\n com.wm" +
      "j.game.common.message.codeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wmj.game.common.message.code.Mid.getDescriptor(),
          com.wmj.game.common.message.code.ErrorCode.getDescriptor(),
        }, assigner);
    internal_static_ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ping_descriptor,
        new java.lang.String[] { "Mid", });
    internal_static_pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_descriptor,
        new java.lang.String[] { "Mid", "ErrorCode", "SystemTime", });
    com.wmj.game.common.message.code.Mid.getDescriptor();
    com.wmj.game.common.message.code.ErrorCode.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
