// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mid.proto

package com.wmj.game.common.message.code;

public final class Mid {
  private Mid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *1-5000 		        内部消息
   *5001-10000            网关消息
   *10001-10002           大厅消息
   *20001-99999           游戏消息
   * </pre>
   *
   * Protobuf enum {@code MID}
   */
  public enum MID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknow = 0;</code>
     */
    Unknow(0),
    /**
     * <pre>
     *内部
     * </pre>
     *
     * <code>ChangeRoleServerReq = 1005;</code>
     */
    ChangeRoleServerReq(1005),
    /**
     * <pre>
     *改变角色服务器
     * </pre>
     *
     * <code>ChangeRoleServerRes = 1006;</code>
     */
    ChangeRoleServerRes(1006),
    /**
     * <pre>
     *网关
     * </pre>
     *
     * <code>Ping = 5001;</code>
     */
    Ping(5001),
    /**
     * <pre>
     *ping返回
     * </pre>
     *
     * <code>Pong = 5002;</code>
     */
    Pong(5002),
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>LoginReq = 10001;</code>
     */
    LoginReq(10001),
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LoginRes = 10002;</code>
     */
    LoginRes(10002),
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>QuitReq = 10007;</code>
     */
    QuitReq(10007),
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>QuitRes = 10008;</code>
     */
    QuitRes(10008),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknow = 0;</code>
     */
    public static final int Unknow_VALUE = 0;
    /**
     * <pre>
     *内部
     * </pre>
     *
     * <code>ChangeRoleServerReq = 1005;</code>
     */
    public static final int ChangeRoleServerReq_VALUE = 1005;
    /**
     * <pre>
     *改变角色服务器
     * </pre>
     *
     * <code>ChangeRoleServerRes = 1006;</code>
     */
    public static final int ChangeRoleServerRes_VALUE = 1006;
    /**
     * <pre>
     *网关
     * </pre>
     *
     * <code>Ping = 5001;</code>
     */
    public static final int Ping_VALUE = 5001;
    /**
     * <pre>
     *ping返回
     * </pre>
     *
     * <code>Pong = 5002;</code>
     */
    public static final int Pong_VALUE = 5002;
    /**
     * <pre>
     *大厅
     * </pre>
     *
     * <code>LoginReq = 10001;</code>
     */
    public static final int LoginReq_VALUE = 10001;
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LoginRes = 10002;</code>
     */
    public static final int LoginRes_VALUE = 10002;
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>QuitReq = 10007;</code>
     */
    public static final int QuitReq_VALUE = 10007;
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>QuitRes = 10008;</code>
     */
    public static final int QuitRes_VALUE = 10008;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MID valueOf(int value) {
      return forNumber(value);
    }

    public static MID forNumber(int value) {
      switch (value) {
        case 0: return Unknow;
        case 1005: return ChangeRoleServerReq;
        case 1006: return ChangeRoleServerRes;
        case 5001: return Ping;
        case 5002: return Pong;
        case 10001: return LoginReq;
        case 10002: return LoginRes;
        case 10007: return QuitReq;
        case 10008: return QuitRes;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MID>() {
            public MID findValueByNumber(int number) {
              return MID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wmj.game.common.message.code.Mid.getDescriptor().getEnumTypes().get(0);
    }

    private static final MID[] VALUES = values();

    public static MID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMid.proto*\225\001\n\003MID\022\n\n\006Unknow\020\000\022\030\n\023Chang" +
      "eRoleServerReq\020\355\007\022\030\n\023ChangeRoleServerRes" +
      "\020\356\007\022\t\n\004Ping\020\211\'\022\t\n\004Pong\020\212\'\022\r\n\010LoginReq\020\221N" +
      "\022\r\n\010LoginRes\020\222N\022\014\n\007QuitReq\020\227N\022\014\n\007QuitRes" +
      "\020\230NB\"\n com.wmj.game.common.message.codeb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
