// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameRpc.proto

package com.wmj.game.engine.rpc.proto;

public final class GameRpc {
  private GameRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Behavior}
   */
  public enum Behavior
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Handle = 0;</code>
     */
    Handle(0),
    /**
     * <code>Logout = 1;</code>
     */
    Logout(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Handle = 0;</code>
     */
    public static final int Handle_VALUE = 0;
    /**
     * <code>Logout = 1;</code>
     */
    public static final int Logout_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Behavior valueOf(int value) {
      return forNumber(value);
    }

    public static Behavior forNumber(int value) {
      switch (value) {
        case 0: return Handle;
        case 1: return Logout;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Behavior>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Behavior> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Behavior>() {
            public Behavior findValueByNumber(int number) {
              return Behavior.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wmj.game.engine.rpc.proto.GameRpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final Behavior[] VALUES = values();

    public static Behavior valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Behavior(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Behavior)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 sessionId = 1;</code>
     */
    long getSessionId();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>.Behavior behavior = 3;</code>
     */
    int getBehaviorValue();
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      sessionId_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      behavior_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sessionId_ = input.readInt64();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              behavior_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.engine.rpc.proto.GameRpc.Request.class, com.wmj.game.engine.rpc.proto.GameRpc.Request.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int BEHAVIOR_FIELD_NUMBER = 3;
    private int behavior_;
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    public int getBehaviorValue() {
      return behavior_;
    }
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    public com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior() {
      @SuppressWarnings("deprecation")
      com.wmj.game.engine.rpc.proto.GameRpc.Behavior result = com.wmj.game.engine.rpc.proto.GameRpc.Behavior.valueOf(behavior_);
      return result == null ? com.wmj.game.engine.rpc.proto.GameRpc.Behavior.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (behavior_ != com.wmj.game.engine.rpc.proto.GameRpc.Behavior.Handle.getNumber()) {
        output.writeEnum(3, behavior_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (behavior_ != com.wmj.game.engine.rpc.proto.GameRpc.Behavior.Handle.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, behavior_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.engine.rpc.proto.GameRpc.Request)) {
        return super.equals(obj);
      }
      com.wmj.game.engine.rpc.proto.GameRpc.Request other = (com.wmj.game.engine.rpc.proto.GameRpc.Request) obj;

      boolean result = true;
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && getData()
          .equals(other.getData());
      result = result && behavior_ == other.behavior_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + BEHAVIOR_FIELD_NUMBER;
      hash = (53 * hash) + behavior_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.engine.rpc.proto.GameRpc.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        com.wmj.game.engine.rpc.proto.GameRpc.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.engine.rpc.proto.GameRpc.Request.class, com.wmj.game.engine.rpc.proto.GameRpc.Request.Builder.class);
      }

      // Construct using com.wmj.game.engine.rpc.proto.GameRpc.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        behavior_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Request_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Request getDefaultInstanceForType() {
        return com.wmj.game.engine.rpc.proto.GameRpc.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Request build() {
        com.wmj.game.engine.rpc.proto.GameRpc.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Request buildPartial() {
        com.wmj.game.engine.rpc.proto.GameRpc.Request result = new com.wmj.game.engine.rpc.proto.GameRpc.Request(this);
        result.sessionId_ = sessionId_;
        result.data_ = data_;
        result.behavior_ = behavior_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.engine.rpc.proto.GameRpc.Request) {
          return mergeFrom((com.wmj.game.engine.rpc.proto.GameRpc.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.engine.rpc.proto.GameRpc.Request other) {
        if (other == com.wmj.game.engine.rpc.proto.GameRpc.Request.getDefaultInstance()) return this;
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.behavior_ != 0) {
          setBehaviorValue(other.getBehaviorValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.engine.rpc.proto.GameRpc.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.engine.rpc.proto.GameRpc.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int behavior_ = 0;
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public int getBehaviorValue() {
        return behavior_;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder setBehaviorValue(int value) {
        behavior_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior() {
        @SuppressWarnings("deprecation")
        com.wmj.game.engine.rpc.proto.GameRpc.Behavior result = com.wmj.game.engine.rpc.proto.GameRpc.Behavior.valueOf(behavior_);
        return result == null ? com.wmj.game.engine.rpc.proto.GameRpc.Behavior.UNRECOGNIZED : result;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder setBehavior(com.wmj.game.engine.rpc.proto.GameRpc.Behavior value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        behavior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder clearBehavior() {
        
        behavior_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final com.wmj.game.engine.rpc.proto.GameRpc.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.engine.rpc.proto.GameRpc.Request();
    }

    public static com.wmj.game.engine.rpc.proto.GameRpc.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.engine.rpc.proto.GameRpc.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 sessionId = 1;</code>
     */
    long getSessionId();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>.Behavior behavior = 3;</code>
     */
    int getBehaviorValue();
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior();

    /**
     * <code>int32 errorCode = 4;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      sessionId_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      behavior_ = 0;
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sessionId_ = input.readInt64();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              behavior_ = rawValue;
              break;
            }
            case 32: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wmj.game.engine.rpc.proto.GameRpc.Response.class, com.wmj.game.engine.rpc.proto.GameRpc.Response.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int BEHAVIOR_FIELD_NUMBER = 3;
    private int behavior_;
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    public int getBehaviorValue() {
      return behavior_;
    }
    /**
     * <code>.Behavior behavior = 3;</code>
     */
    public com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior() {
      @SuppressWarnings("deprecation")
      com.wmj.game.engine.rpc.proto.GameRpc.Behavior result = com.wmj.game.engine.rpc.proto.GameRpc.Behavior.valueOf(behavior_);
      return result == null ? com.wmj.game.engine.rpc.proto.GameRpc.Behavior.UNRECOGNIZED : result;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0L) {
        output.writeInt64(1, sessionId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (behavior_ != com.wmj.game.engine.rpc.proto.GameRpc.Behavior.Handle.getNumber()) {
        output.writeEnum(3, behavior_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(4, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (behavior_ != com.wmj.game.engine.rpc.proto.GameRpc.Behavior.Handle.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, behavior_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wmj.game.engine.rpc.proto.GameRpc.Response)) {
        return super.equals(obj);
      }
      com.wmj.game.engine.rpc.proto.GameRpc.Response other = (com.wmj.game.engine.rpc.proto.GameRpc.Response) obj;

      boolean result = true;
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && getData()
          .equals(other.getData());
      result = result && behavior_ == other.behavior_;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + BEHAVIOR_FIELD_NUMBER;
      hash = (53 * hash) + behavior_;
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wmj.game.engine.rpc.proto.GameRpc.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wmj.game.engine.rpc.proto.GameRpc.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.wmj.game.engine.rpc.proto.GameRpc.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wmj.game.engine.rpc.proto.GameRpc.Response.class, com.wmj.game.engine.rpc.proto.GameRpc.Response.Builder.class);
      }

      // Construct using com.wmj.game.engine.rpc.proto.GameRpc.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        behavior_ = 0;

        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wmj.game.engine.rpc.proto.GameRpc.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Response getDefaultInstanceForType() {
        return com.wmj.game.engine.rpc.proto.GameRpc.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Response build() {
        com.wmj.game.engine.rpc.proto.GameRpc.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wmj.game.engine.rpc.proto.GameRpc.Response buildPartial() {
        com.wmj.game.engine.rpc.proto.GameRpc.Response result = new com.wmj.game.engine.rpc.proto.GameRpc.Response(this);
        result.sessionId_ = sessionId_;
        result.data_ = data_;
        result.behavior_ = behavior_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wmj.game.engine.rpc.proto.GameRpc.Response) {
          return mergeFrom((com.wmj.game.engine.rpc.proto.GameRpc.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wmj.game.engine.rpc.proto.GameRpc.Response other) {
        if (other == com.wmj.game.engine.rpc.proto.GameRpc.Response.getDefaultInstance()) return this;
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.behavior_ != 0) {
          setBehaviorValue(other.getBehaviorValue());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wmj.game.engine.rpc.proto.GameRpc.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wmj.game.engine.rpc.proto.GameRpc.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 1;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int behavior_ = 0;
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public int getBehaviorValue() {
        return behavior_;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder setBehaviorValue(int value) {
        behavior_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public com.wmj.game.engine.rpc.proto.GameRpc.Behavior getBehavior() {
        @SuppressWarnings("deprecation")
        com.wmj.game.engine.rpc.proto.GameRpc.Behavior result = com.wmj.game.engine.rpc.proto.GameRpc.Behavior.valueOf(behavior_);
        return result == null ? com.wmj.game.engine.rpc.proto.GameRpc.Behavior.UNRECOGNIZED : result;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder setBehavior(com.wmj.game.engine.rpc.proto.GameRpc.Behavior value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        behavior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Behavior behavior = 3;</code>
       */
      public Builder clearBehavior() {
        
        behavior_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.wmj.game.engine.rpc.proto.GameRpc.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wmj.game.engine.rpc.proto.GameRpc.Response();
    }

    public static com.wmj.game.engine.rpc.proto.GameRpc.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wmj.game.engine.rpc.proto.GameRpc.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgameRpc.proto\"G\n\007Request\022\021\n\tsessionId\030" +
      "\001 \001(\003\022\014\n\004data\030\002 \001(\014\022\033\n\010behavior\030\003 \001(\0162\t." +
      "Behavior\"[\n\010Response\022\021\n\tsessionId\030\001 \001(\003\022" +
      "\014\n\004data\030\002 \001(\014\022\033\n\010behavior\030\003 \001(\0162\t.Behavi" +
      "or\022\021\n\terrorCode\030\004 \001(\005*\"\n\010Behavior\022\n\n\006Han" +
      "dle\020\000\022\n\n\006Logout\020\00122\n\013GameService\022#\n\006hand" +
      "le\022\010.Request\032\t.Response\"\000(\0010\001B\037\n\035com.wmj" +
      ".game.engine.rpc.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "SessionId", "Data", "Behavior", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "SessionId", "Data", "Behavior", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
