spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minigame?charsetEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: Root123456*
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select now()
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 50