// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.wmj.game.common.message.code.nano;

@SuppressWarnings("hiding")
public interface ErrorCode {

  // enum ErrorCode
  public static final int Success = 0;
}
