// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.wmj.game.common.message.code.nano;

@SuppressWarnings("hiding")
public interface Mid {

  // enum MID
  public static final int Unknow = 0;
  public static final int ChangeRoleServerReq = 1005;
  public static final int ChangeRoleServerRes = 1006;
  public static final int Ping = 5001;
  public static final int Pong = 5002;
  public static final int LoginReq = 10001;
  public static final int LoginRes = 10002;
  public static final int QuitReq = 10007;
  public static final int QuitRes = 10008;
}
